default_language_version:
  python: python3.13

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system  # language: system tells pre-commit to run these hooks in current shell environment, not inside a pre-commit-managed virtualenv.
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]